"""Install the Hermes gateway startup hook that keeps this server resident.

Hermes fires ``gateway:startup`` hooks from ``<hermes home>/hooks/<name>/``
(``HOOK.yaml`` + ``handler.py``) every time the messaging gateway boots.  Pointing
Hermes *at* this server is only half the wiring: the Jev plugin calls it on every
turn, so something has to make sure it is listening whenever the gateway is.  That
is this module.

The hook written here is stdlib-only and runs inside the gateway process.  It
probes ``/health`` first and leaves a live listener alone, refuses to start a
second server when the port is held by something that is not Laya, spawns the
server detached (so a gateway restart finds it already up) and waits for
``ready`` on a background thread so gateway startup is never blocked.

Layout written::

    <hermes home>/hooks/laya-startup/HOOK.yaml
    <hermes home>/hooks/laya-startup/handler.py

``laya-for-agents install-gateway-hook`` writes them;
``laya-for-agents uninstall-gateway-hook`` removes them;
``laya-for-agents setup-hermes`` does it as part of the full wiring.
"""
from __future__ import annotations

import os
import shutil
import string
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import List, Optional

HOOK_NAME = "laya-startup"
HOOK_EVENTS = ("gateway:startup",)
HANDLER_MARKER = "Generated by laya-for-agents"
DISABLE_ENV = "LFA_GATEWAY_AUTOSTART"

HOOK_YAML = f"""name: {HOOK_NAME}
description: Starts the Laya local decision server (Jev /v1/systemone) on Gateway startup
events:
  - gateway:startup
"""

# Substituted with string.Template, so every literal ``$`` inside would need
# escaping -- there are none.
HANDLER_TEMPLATE = '''"""Start the Laya local decision server when the Hermes gateway boots.

${MARKER} ${VERSION} -- reinstall or refresh with:

    laya-for-agents install-gateway-hook

Laya serves the TypeSafe Jev ``/v1/systemone`` wire protocol (the URL
``TYPESAFE_BASE_URL`` in the Hermes ``.env`` points at).  The hermes-jev plugin
calls it on every turn, so it needs to be resident whenever the gateway is.

Runs inside the gateway process: stdlib only, no imports from the Laya venv.
The server is spawned detached so it survives gateway restarts, and an existing
listener is always detected and left alone.

Override without editing this file:
  LFA_GATEWAY_AUTOSTART=off   skip autostart entirely
  LFA_PROJECT_ROOT=<dir>      serve from another checkout
  LFA_PYTHON=<exe>            use another interpreter
  LFA_HOST / LFA_PORT         bind somewhere else
"""
from __future__ import annotations

import json
import logging
import os
import socket
import subprocess
import sys
import threading
import time
import urllib.request
from pathlib import Path
from typing import Optional
from urllib.parse import urlsplit

logger = logging.getLogger("hooks.${HOOK_NAME}")

HOOK_VERSION = "${VERSION}"

PROJECT_ROOT = Path(os.environ.get("LFA_PROJECT_ROOT") or r"${PROJECT_ROOT}")
PYTHON = Path(os.environ.get("LFA_PYTHON") or r"${PYTHON}")
LOG_FILE = Path(r"${LOG_FILE}")
BASE_URL = "${BASE_URL}"

DEFAULT_HOST = "127.0.0.1"
DEFAULT_PORT = 8000
READY_TIMEOUT_S = 900
POLL_INTERVAL_S = 2.0

_proc: Optional[subprocess.Popen] = None
_log_handle = None


def _log(msg: str) -> None:
    """Append a line to the hook log so startup behaviour is verifiable."""
    line = f"{time.strftime('%Y-%m-%d %H:%M:%S')} {msg}"
    logger.info("${HOOK_NAME}: %s", msg)
    try:
        LOG_FILE.parent.mkdir(parents=True, exist_ok=True)
        with open(LOG_FILE, "a", encoding="utf-8") as fh:
            fh.write(line + "\\n")
    except Exception:
        pass


def _target() -> tuple[str, int, str]:
    """(host, port, base_url) -- the loopback endpoint this server should serve.

    Honours ``TYPESAFE_BASE_URL`` when it points at numeric loopback (the only
    plaintext shape the Jev client accepts) so a moved port is followed
    automatically; anything else falls back to the baked default so we never
    fight another endpoint for a port.
    """
    raw = os.environ.get("TYPESAFE_BASE_URL", "").strip()
    host = os.environ.get("LFA_HOST", "").strip() or DEFAULT_HOST
    try:
        port = int(os.environ.get("LFA_PORT", "") or DEFAULT_PORT)
    except ValueError:
        port = DEFAULT_PORT
    parts = urlsplit(BASE_URL)
    if parts.hostname in (DEFAULT_HOST, "localhost", "::1") and parts.port:
        host, port = parts.hostname, parts.port
    if raw:
        override = urlsplit(raw)
        if override.hostname in (DEFAULT_HOST, "localhost", "::1"):
            host = override.hostname
            if override.port:
                port = override.port
    return host, port, f"http://{host}:{port}"


def _health(base_url: str, timeout: float = 2.5) -> Optional[dict]:
    """The server's /health body, or None when nothing answers *as this server*."""
    try:
        with urllib.request.urlopen(f"{base_url}/health", timeout=timeout) as resp:
            if resp.status != 200:
                return None
            body = json.loads(resp.read().decode("utf-8", "replace"))
    except Exception:
        return None
    # A 200 from somebody else's server on this port is not ours to reuse.
    if isinstance(body, dict) and body.get("service") == "laya-for-agents":
        return body
    return None


def _port_open(host: str, port: int, timeout: float = 0.6) -> bool:
    try:
        with socket.create_connection((host, port), timeout=timeout):
            return True
    except OSError:
        return False


def _spawn(host: str, port: int) -> Optional[subprocess.Popen]:
    """Launch ``python -m laya_for_agents.cli serve`` detached, logging to file."""
    global _log_handle
    try:
        LOG_FILE.parent.mkdir(parents=True, exist_ok=True)
        _log_handle = open(LOG_FILE, "a", encoding="utf-8", buffering=1)
    except Exception:
        _log_handle = None
    flags = 0
    if sys.platform == "win32":
        flags = 0x00000008 | 0x00000200  # DETACHED_PROCESS | CREATE_NEW_PROCESS_GROUP
    env = dict(os.environ)
    env["PYTHONUNBUFFERED"] = "1"
    env["PYTHONUTF8"] = "1"
    env.pop("VIRTUAL_ENV", None)
    cwd = str(PROJECT_ROOT) if PROJECT_ROOT.is_dir() else None
    try:
        return subprocess.Popen(
            [str(PYTHON), "-m", "laya_for_agents.cli", "serve", "--host", host, "--port", str(port)],
            cwd=cwd,
            stdin=subprocess.DEVNULL,
            stdout=_log_handle or subprocess.DEVNULL,
            stderr=subprocess.STDOUT if _log_handle else subprocess.DEVNULL,
            creationflags=flags,
            start_new_session=True,
            env=env,
            close_fds=True,
        )
    except Exception as exc:
        _log(f"launch failed: {exc}")
        return None


def _await_ready(base_url: str) -> None:
    """Poll /health until checkpoints are resident, reporting once."""
    started = time.time()
    announced_loading = False
    while time.time() - started < READY_TIMEOUT_S:
        body = _health(base_url)
        if body and body.get("ready"):
            _log(
                f"ready in {time.time() - started:.1f}s -- device={body.get('device')} "
                f"revisions={body.get('revisions')}"
            )
            return
        if body and not announced_loading:
            announced_loading = True
            _log(f"port is serving, checkpoints still loading ({body.get('loading_for_s')}s)")
        if _proc is not None and _proc.poll() is not None and not _port_open(*_host_port(base_url)):
            _log(f"server exited with code {_proc.returncode} before becoming ready")
            return
        time.sleep(POLL_INTERVAL_S)
    _log(f"still not ready after {READY_TIMEOUT_S}s -- check {LOG_FILE}")


def _host_port(base_url: str) -> tuple[str, int]:
    parts = urlsplit(base_url)
    return (parts.hostname or DEFAULT_HOST, parts.port or DEFAULT_PORT)


async def handle(event_type: str, context: dict) -> None:
    """Fired by the gateway on ``gateway:startup``."""
    if (os.environ.get("${DISABLE_ENV}") or "").strip().lower() in {"off", "0", "false", "no"}:
        _log(f"${DISABLE_ENV} is off -- not starting the server")
        return

    host, port, base_url = _target()

    existing = _health(base_url)
    if existing is not None:
        _log(f"already running on {base_url} (ready={existing.get('ready')}) -- nothing to do")
        return

    if _port_open(host, port):
        _log(f"port {host}:{port} is busy but does not answer as Laya -- not starting a second server")
        return

    if not PYTHON.exists():
        _log(f"interpreter missing: {PYTHON}")
        return

    global _proc
    _log(f"hook fired ({event_type}) -- starting Laya on {base_url}")
    _proc = _spawn(host, port)
    if _proc is None:
        return
    _log(f"spawned pid {_proc.pid}")

    threading.Thread(target=_await_ready, args=(base_url,), name="${HOOK_NAME}-wait", daemon=True).start()
'''


@dataclass
class HookInstall:
    """What an install/uninstall did, for the CLI to report."""

    home: Path
    directory: Path
    handler: Path
    manifest: Path
    log_file: Path
    changed: List[str]
    dry_run: bool = False

    @property
    def installed(self) -> bool:
        return self.manifest.is_file() and self.handler.is_file()


def hermes_homes() -> List[Path]:
    """Every Hermes home on this machine, most specific first.

    Windows keeps the active profile under ``%LOCALAPPDATA%\\hermes``; elsewhere
    it is ``~/.hermes``. A profile home is preferred over the shared root because
    that is where the running gateway reads its ``.env`` and its ``hooks/``.
    """
    out: List[Path] = []
    env_home = os.environ.get("HERMES_HOME")
    if env_home:
        out.append(Path(env_home))
    local = os.environ.get("LOCALAPPDATA")
    if local:
        out.append(Path(local) / "hermes")
    out.append(Path.home() / ".hermes")
    seen, unique = set(), []
    for path in out:
        key = str(path).lower()
        if key not in seen:
            seen.add(key)
            unique.append(path)
    return unique


def find_hermes_home() -> Optional[Path]:
    """The home a running gateway would use, or None when Hermes is absent."""
    candidates = hermes_homes()
    for home in candidates:
        if (home / "config.yaml").is_file() or (home / ".env").is_file():
            return home
    for home in candidates:
        if home.is_dir():
            return home
    return None


def hooks_dir(home: Path) -> Path:
    return Path(home) / "hooks"


def hook_dir(home: Path) -> Path:
    return hooks_dir(home) / HOOK_NAME


def _version() -> str:
    try:
        from . import __version__ as version  # type: ignore[attr-defined]

        return str(version)
    except Exception:  # noqa: BLE001 - informational only
        return "unknown"


def render_handler(*, project_root: Path, python_exe: Path, base_url: str, log_file: Path) -> str:
    """The ``handler.py`` body for one machine's paths."""
    template = string.Template(HANDLER_TEMPLATE)
    return template.substitute(
        MARKER=HANDLER_MARKER,
        VERSION=_version(),
        HOOK_NAME=HOOK_NAME,
        DISABLE_ENV=DISABLE_ENV,
        PROJECT_ROOT=str(project_root),
        PYTHON=str(python_exe),
        BASE_URL=base_url.rstrip("/"),
        LOG_FILE=str(log_file),
    )


def default_log_file(home: Path, project_root: Path) -> Path:
    """Where the hook appends its lines: next to the server, else in the home."""
    if project_root.is_dir() and os.access(project_root, os.W_OK):
        return project_root / "laya_gateway_startup.log"
    return Path(home) / "laya_gateway_startup.log"


def install_gateway_hook(
    home: Optional[Path] = None,
    *,
    project_root: Optional[Path] = None,
    python_exe: Optional[Path] = None,
    base_url: Optional[str] = None,
    log_file: Optional[Path] = None,
    dry_run: bool = False,
) -> HookInstall:
    """Write the ``gateway:startup`` hook into a Hermes home. Idempotent."""
    home = Path(home) if home else find_hermes_home()
    if home is None:
        raise RuntimeError("no Hermes home found -- is Hermes installed on this machine?")
    root = Path(project_root) if project_root else Path(__file__).resolve().parent.parent
    exe = Path(python_exe) if python_exe else Path(sys.executable)
    url = base_url or "http://127.0.0.1:8000"
    log = Path(log_file) if log_file else default_log_file(home, root)

    directory = hook_dir(home)
    manifest, handler = directory / "HOOK.yaml", directory / "handler.py"
    body = render_handler(project_root=root, python_exe=exe, base_url=url, log_file=log)

    changed: List[str] = []
    if not manifest.is_file() or manifest.read_text(encoding="utf-8") != HOOK_YAML:
        changed.append("HOOK.yaml")
    if not handler.is_file() or handler.read_text(encoding="utf-8") != body:
        changed.append("handler.py")

    if not dry_run and changed:
        directory.mkdir(parents=True, exist_ok=True)
        manifest.write_text(HOOK_YAML, encoding="utf-8")
        handler.write_text(body, encoding="utf-8")

    return HookInstall(home=home, directory=directory, handler=handler, manifest=manifest,
                       log_file=log, changed=changed, dry_run=dry_run)


def uninstall_gateway_hook(home: Optional[Path] = None, *, dry_run: bool = False) -> HookInstall:
    """Remove the hook directory (handler, manifest, bytecode cache) entirely."""
    home = Path(home) if home else find_hermes_home()
    if home is None:
        raise RuntimeError("no Hermes home found -- is Hermes installed on this machine?")
    directory = hook_dir(home)
    changed = [] if not directory.is_dir() else ["removed " + str(directory)]
    if not dry_run and directory.is_dir():
        shutil.rmtree(directory)
    return HookInstall(home=home, directory=directory, handler=directory / "handler.py",
                       manifest=directory / "HOOK.yaml",
                       log_file=default_log_file(home, Path(__file__).resolve().parent.parent),
                       changed=changed, dry_run=dry_run)


def gateway_hook_status(home: Optional[Path] = None) -> dict:
    """Whether the hook is present, and for which server it was generated."""
    home = Path(home) if home else find_hermes_home()
    if home is None:
        return {"hermes_home": None, "installed": False, "reason": "no Hermes home found"}
    directory = hook_dir(home)
    handler = directory / "handler.py"
    manifest = directory / "HOOK.yaml"
    info = {
        "hermes_home": str(home),
        "directory": str(directory),
        "installed": handler.is_file() and manifest.is_file(),
        "events": list(HOOK_EVENTS),
    }
    if handler.is_file():
        text = handler.read_text(encoding="utf-8", errors="replace")
        for line in text.splitlines():
            stripped = line.strip()
            if stripped.startswith("HOOK_VERSION = "):
                info["hook_version"] = stripped.split("=", 1)[1].strip().strip('"')
            elif stripped.startswith("BASE_URL = "):
                info["base_url"] = stripped.split("=", 1)[1].strip().strip('"')
    return info
